services:
  - type: web
    name: storehub-qms
    env: node
    region: oregon
    plan: free # Start with free plan, upgrade as needed
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_DOMAIN
        value: storehubqms.com
      - key: SUPERADMIN_DOMAIN
        value: admin.storehubqms.com
      - key: DATABASE_URL
        fromDatabase:
          name: storehub-qms-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: RENDER_API_KEY
        sync: false # Set manually in dashboard
      - key: RENDER_SERVICE_ID
        sync: false # Set after first deploy
      - key: EMAIL_PROVIDER
        value: console # Change to sendgrid/ses for production
      - key: EMAIL_FROM
        value: noreply@storehubqms.com
      - key: TRUST_PROXY
        value: true

databases:
  - name: storehub-qms-db
    databaseName: storehub_qms
    user: storehub_qms
    region: oregon
    plan: free # Start with free plan, upgrade as needed

# Note: Custom domains are configured through Render dashboard
# After deployment:
# 1. Add storehubqms.com as custom domain
# 2. Add *.storehubqms.com for wildcard subdomains
# 3. Update DNS records as instructed by Render