#!/bin/bash

echo "🔧 SESSION TABLE MIGRATION SCRIPT"
echo "================================="
echo ""
echo "This script will rename the session table columns to fix the schema mismatch."
echo ""
echo "You need your Render PostgreSQL External Database URL to run this."
echo ""
echo "To get it:"
echo "1. Go to https://dashboard.render.com"
echo "2. Click on your PostgreSQL database service"
echo "3. Copy the 'External Database URL' from the Connections section"
echo ""
echo "Then run:"
echo "  psql 'YOUR_EXTERNAL_DATABASE_URL' < fix-session-columns.sql"
echo ""
echo "Or if you have the URL in an environment variable:"
echo "  psql \$DATABASE_URL < fix-session-columns.sql"
echo ""
echo "The migration SQL will:"
echo "- Rename 'data' column to 'sess'"
echo "- Rename 'expiresAt' column to 'expire'"
echo ""
echo "After running the migration:"
echo "1. Commit and push the code changes"
echo "2. Render will deploy automatically"
echo "3. Login functionality will be restored"